version: '3'
services:
  piston:
    build: .
    ports:
      - "5000:5000"
    environment:
      EMAIL_ADDRESS: ${EMAIL_ADDRESS}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      RECIPIENT_EMAIL: ${RECIPIENT_EMAIL}
    volumes:
      - ${HOST_PLUGINS_PATH}:/piston/plugins
